function radar () {
    pins.servoWritePin(AnalogPin.P0, 34)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 35)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 40)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 50)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 120)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 140)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 120)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 70)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P0, 50)
    basic.pause(100)
    pins.servoWritePin(AnalogPin.P0, 40)
    basic.pause(100)
    pins.servoWritePin(AnalogPin.P0, 30)
    basic.pause(100)
    pins.servoWritePin(AnalogPin.P0, 29)
    basic.pause(100)
    pins.servoWritePin(AnalogPin.P0, 28)
}
let distance = 0
DFRobotMaqueenPlusV2.init()
basic.forever(function () {
    radar()
    distance = DFRobotMaqueenPlusV2.readUltrasonic(DigitalPin.P13, DigitalPin.P14)
    if (distance < 50) {
        DFRobotMaqueenPlusV2.controlLED(MyEnumLed.eAllLed, MyEnumSwitch.eOpen)
        DFRobotMaqueenPlusV2.controlMotor(MyEnumMotor.eLeftMotor, MyEnumDir.eForward, 100)
        basic.pause(1000)
        DFRobotMaqueenPlusV2.controlMotor(MyEnumMotor.eAllMotor, MyEnumDir.eBackward, 100)
        basic.pause(1000)
    } else {
        DFRobotMaqueenPlusV2.controlLED(MyEnumLed.eAllLed, MyEnumSwitch.eClose)
        DFRobotMaqueenPlusV2.controlMotor(MyEnumMotor.eAllMotor, MyEnumDir.eForward, 100)
    }
})
